/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemanagement;


/**
 *
 * @author devangbafna
 */
public class MainFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        //rightPanel.add(new AdmissionFormPanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addViewBatchesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addViewLecturesButton = new javax.swing.JButton();
        takeAttendanceButton = new javax.swing.JButton();
        viewAttendanceButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        addViewStudentsButton = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        leftPanel.setBackground(java.awt.Color.darkGray);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admissions:");

        addViewBatchesButton.setText("Add / View Batches");
        addViewBatchesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViewBatchesButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lectures: ");

        addViewLecturesButton.setText("Add/ View Lectures");
        addViewLecturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViewLecturesButtonActionPerformed(evt);
            }
        });

        takeAttendanceButton.setText("Take Attendance");
        takeAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeAttendanceButtonActionPerformed(evt);
            }
        });

        viewAttendanceButton.setText("View Attendance");
        viewAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttendanceButtonActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Attendance:");

        addViewStudentsButton.setText("Add/ View Students");
        addViewStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addViewStudentsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(viewAttendanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addViewLecturesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(takeAttendanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addViewStudentsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(addViewBatchesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addViewBatchesButton)
                .addGap(18, 18, 18)
                .addComponent(addViewStudentsButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addViewLecturesButton)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(takeAttendanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewAttendanceButton)
                .addContainerGap(527, Short.MAX_VALUE))
        );

        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setBackground(java.awt.Color.darkGray);
        rightPanel.setForeground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(rightPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addViewStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViewStudentsButtonActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        rightPanel.add(new AddViewStudentsPanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_addViewStudentsButtonActionPerformed

    private void viewAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttendanceButtonActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        rightPanel.add(new ViewAttendancePanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_viewAttendanceButtonActionPerformed

    private void takeAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeAttendanceButtonActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        rightPanel.add(new TakeAttendancePanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_takeAttendanceButtonActionPerformed

    private void addViewLecturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViewLecturesButtonActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        rightPanel.add(new AddViewLecturesPanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_addViewLecturesButtonActionPerformed

    private void addViewBatchesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addViewBatchesButtonActionPerformed
        rightPanel.removeAll();
        rightPanel.repaint();
        rightPanel.revalidate();
        rightPanel.add(new AddViewBatchesPanel());
        rightPanel.repaint();
        rightPanel.revalidate();
    }//GEN-LAST:event_addViewBatchesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addViewBatchesButton;
    private javax.swing.JButton addViewLecturesButton;
    private javax.swing.JButton addViewStudentsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton takeAttendanceButton;
    private javax.swing.JButton viewAttendanceButton;
    // End of variables declaration//GEN-END:variables
}
